Repository moul/gotty-client, pull requests merged in 2020-11, with the labels that each got.

#99 feat: handle syscall.EINTR
  gotty-client.go
Labels: enhancement, ✅ Approved

#103 feat: add goreleaser config + update manual install instructions
  .goreleaser.yml
  README.md
Labels: enhancement

#105 fix: escaped basic token
  gotty-client.go
Labels: bug

#108 [#107] fix: escaped basic token on /ws
  gotty-client.go
Labels: bug
